### ISSUE TITLE
Cache options ignored, wunderground responses are cached with infinite TTL

### ISSUE THREAD

**Issue by barwin** [patrickvalle/wundergrounded#2]
Hello,

First off, thanks for publishing this module!

I've discovered a problem where the options to NodeCache are being passed improperly, and are thus ignored.  NodeCache then ends up caching wunderground responses with no TTL. The effect is that any users that enable caching will only hit the API once and that response will live for the life of the app.

I've opened #1 to fix this issue.

Thanks,
-Ben

**Comment by patrickvalle** [comment]
@barwin Hey man- sorry this took so long to get to. Merged https://github.com/patrickvalle/wundergrounded/pull/1. Thanks for the contribution!

**Comment by barwin** [comment]
No worries, I know how it goes. Thanks!
